services:
  frontend:
    build:
      context: ./builds/angular-cli
    working_dir: /app
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ../../src/frontend:/app

  admin-panel:
    build:
      context: ./builds/angular-cli
    working_dir: /app
    command: ng serve --host 0.0.0.0
    ports:
      - 4201:4200
    volumes:
      - ../../src/admin-panel:/app

  backend:
    build:
      context: ./builds/nest-cli
    working_dir: /app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      AUTH_SERVICE_HOST: auth-service
      AUTH_SERVICE_PORT: 3000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    volumes:
      - ../../src/backend:/app
  
  auth-service:
    build:
      context: ./builds/nest-cli
    working_dir: /app
    command: npm run start:dev
    volumes:
      - ../../src/auth-service:/app
  
  message-service:
    build:
      context: ./builds/nest-cli
    working_dir: /app
    command: npm run start:dev
    volumes:
      - ../../src/message-service:/app

  mongo:
    build:
      context: ./builds/mongo/
    volumes:
      - ../../data/mongo:/data/db